project:
  type: website
  output-dir: docs

website:
  title: "Data Bridge"
  favicon: images/db2.svg
  navbar:
    # title: False
    # logo: images/db2.svg
    left:
      - text: Blog
        href: blog.qmd
        
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/bridgernorman/
      - icon: github
        href: https://github.com/bridger-norman
    
    # page-footer: "Copyright 2024, Bridger Norman" 
    #   background: light
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



