project:
  type: website
  output-dir: docs

website:
  title: "Data Bridge"
  favicon: db2.png
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog
        icon: db2.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



