project:
  type: website
  output-dir: docs

website:
  title: "Data Bridge"
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



